networks:
  kong-net:
    name: kong-networks
    driver: bridge

volumes:
  kong_data: {}

services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    build:
      context: ./config
      dockerfile: Dockerfile
    container_name: kong
    restart: unless-stopped
    networks:
      # kong-net:
      # ipv4_address: 172.1.1.40
      - kong-net
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ./config/kong.yaml:/usr/local/kong/declarative/kong.yml
